# Generated by Django 5.1.2 on 2024-10-24 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0003_alter_compteenbanque_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteenbanque',
            name='rib',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
