# Generated by Django 5.1.2 on 2024-10-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0004_compteenbanque_rib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteenbanque',
            name='prenom',
        ),
    ]
