# Generated by Django 5.1.2 on 2024-10-24 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0005_remove_compteenbanque_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virement',
            name='compte_cible',
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte_cible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_cible', to='banques.compteenbanque'),
        ),
    ]
