# Generated by Django 5.1.2 on 2024-10-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0006_remove_virement_compte_cible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteenbanque',
            name='banque',
        ),
        migrations.DeleteModel(
            name='Banque',
        ),
    ]
